CREATE TABLE "GCG_4205_EMPGARNVNDR"(
 "BIRUNID" INTEGER,
 "EMPLOYEE" CHAR(5),
 "NAME_EMPLOYEE" CHAR(30),
 "GARN_CODE" CHAR(1),
 "GARN_DESCRIPTION" CHAR(20),
 "GARN_AMOUNT" NUMERIC(8,2),
 "VENDOR" CHAR(6),
 "NAME_VENDOR" CHAR(30));
